apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::319209208372:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WYFMWNENY1DY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::319209208372:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-07T06:27:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "847"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a02f362a-bc43-4218-a4c4-ceb2e45aafaf
